name: Build Theme
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build Theme
        run: bash build.sh

      - name: Set up Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Create Tag
        run: git tag -a ${{ github.SHA }} -m ""

      - name: Push Tag
        run: git push --tags

      - name: Add files to release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          tag_name: ${{ github.SHA }}
          files: |
            ./dist/discord_inspired.css
            ./dist/discord_inspired.json
