name: Build Theme
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build Theme
        run: bash build.sh

      - name: Add files to release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          files: |
            ./dist/discord_inspired.css
            ./dist/discord_inspired.json
