name: Build Theme
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build Theme
        run: bash build.sh

      - name: Add zips to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*
